name: Daily Job

on:
  schedule:
    - cron:  '50 8 * * *'



jobs:
  build:
    name: build page
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
        
    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Daily Update
      run: python3 daily_update.py
      env:
        LIXINGER_TOKEN: ${{ secrets.LIXINGER_TOKEN }}

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Deploy
    #  uses: peaceiris/actions-gh-pages@v4
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./output 
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'output/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
